#pragma once
#include "SDL2-2.0.4/include/SDL_keycode.h"

enum KeyCodes
{
	K_CODE_UNKNOWN = SDL_Scancode::SDL_SCANCODE_UNKNOWN,

	K_CODE_A = SDL_Scancode::SDL_SCANCODE_A,
	K_CODE_B = SDL_Scancode::SDL_SCANCODE_B,
	K_CODE_C = SDL_Scancode::SDL_SCANCODE_C,
	K_CODE_D = SDL_Scancode::SDL_SCANCODE_D,
	K_CODE_E = SDL_Scancode::SDL_SCANCODE_E,
	K_CODE_F = SDL_Scancode::SDL_SCANCODE_F,
	K_CODE_G = SDL_Scancode::SDL_SCANCODE_G,
	K_CODE_H = SDL_Scancode::SDL_SCANCODE_H,
	K_CODE_I = SDL_Scancode::SDL_SCANCODE_I,
	K_CODE_J = SDL_Scancode::SDL_SCANCODE_J,
	K_CODE_K = SDL_Scancode::SDL_SCANCODE_K,
	K_CODE_L = SDL_Scancode::SDL_SCANCODE_L,
	K_CODE_M = SDL_Scancode::SDL_SCANCODE_M,
	K_CODE_N = SDL_Scancode::SDL_SCANCODE_N,
	K_CODE_O = SDL_Scancode::SDL_SCANCODE_O,
	K_CODE_P = SDL_Scancode::SDL_SCANCODE_P,
	K_CODE_Q = SDL_Scancode::SDL_SCANCODE_Q,
	K_CODE_R = SDL_Scancode::SDL_SCANCODE_R,
	K_CODE_S = SDL_Scancode::SDL_SCANCODE_S,
	K_CODE_T = SDL_Scancode::SDL_SCANCODE_T,
	K_CODE_U = SDL_Scancode::SDL_SCANCODE_U,
	K_CODE_V = SDL_Scancode::SDL_SCANCODE_V,
	K_CODE_W = SDL_Scancode::SDL_SCANCODE_W,
	K_CODE_X = SDL_Scancode::SDL_SCANCODE_X,
	K_CODE_Y = SDL_Scancode::SDL_SCANCODE_Y,
	K_CODE_Z = SDL_Scancode::SDL_SCANCODE_Z,

	K_CODE_UP = SDL_Scancode::SDL_SCANCODE_UP,
	K_CODE_DOWN = SDL_Scancode::SDL_SCANCODE_DOWN,
	K_CODE_LEFT = SDL_Scancode::SDL_SCANCODE_LEFT,
	K_CODE_RIGHT = SDL_Scancode::SDL_SCANCODE_RIGHT,

	K_CODE_1 = SDL_Scancode::SDL_SCANCODE_1,
	K_CODE_2 = SDL_Scancode::SDL_SCANCODE_2,
	K_CODE_3 = SDL_Scancode::SDL_SCANCODE_3,
	K_CODE_4 = SDL_Scancode::SDL_SCANCODE_4,
	K_CODE_5 = SDL_Scancode::SDL_SCANCODE_5,
	K_CODE_6 = SDL_Scancode::SDL_SCANCODE_6,
	K_CODE_7 = SDL_Scancode::SDL_SCANCODE_7,
	K_CODE_8 = SDL_Scancode::SDL_SCANCODE_8,
	K_CODE_9 = SDL_Scancode::SDL_SCANCODE_9,
	K_CODE_0 = SDL_Scancode::SDL_SCANCODE_0,

	K_CODE_RETURN = SDL_Scancode::SDL_SCANCODE_RETURN,
	K_CODE_ESCAPE = SDL_Scancode::SDL_SCANCODE_ESCAPE,
	K_CODE_BACKSPACE = SDL_Scancode::SDL_SCANCODE_BACKSPACE,
	K_CODE_TAB = SDL_Scancode::SDL_SCANCODE_TAB,
	K_CODE_SPACE = SDL_Scancode::SDL_SCANCODE_SPACE,

	K_CODE_MINUS = SDL_Scancode::SDL_SCANCODE_MINUS,
	K_CODE_EQUALS = SDL_Scancode::SDL_SCANCODE_EQUALS,

	K_CODE_LCTRL = SDL_Scancode::SDL_SCANCODE_LCTRL,
	K_CODE_LSHIFT = SDL_Scancode::SDL_SCANCODE_LSHIFT,
	K_CODE_LALT = SDL_Scancode::SDL_SCANCODE_LALT,
	K_CODE_LGUI = SDL_Scancode::SDL_SCANCODE_LGUI,

	K_CODE_RCTRL = SDL_Scancode::SDL_SCANCODE_RCTRL,
	K_CODE_RSHIFT = SDL_Scancode::SDL_SCANCODE_RSHIFT,
	K_CODE_RALT = SDL_Scancode::SDL_SCANCODE_RALT,
	K_CODE_RGUI = SDL_Scancode::SDL_SCANCODE_RGUI,

	K_CODE_MAX = SDL_Scancode::SDL_NUM_SCANCODES,
};